# spring配置
spring:
  profiles:
    active: test
  servlet:
    multipart:
      max-file-size: 1024
      max-request-size: 1024
  jackson:
    date-format: yyyy/MM/dd HH:mm:ss
    time-zone: GMT+8

mybatis:
  type-aliases-package: cn.zhang.diary.model
  mapper-locations: classpath:mapper/*.xml
server:
  port: 8667
